import { createGlobalTheme } from '@vanilla-extract/css';
import { primitiveTokens } from '@styles/tokens.css';

export const vars = createGlobalTheme(':root', {
  color: {
    pageBg: primitiveTokens.color.sky50,
    panelBg: primitiveTokens.color.sky100,
    cardBg: primitiveTokens.color.sky200,
    boardBg: primitiveTokens.color.white,
    boardHoleBg: primitiveTokens.color.sky300,
    tableHeadBg: primitiveTokens.color.sky300,
    borderSoft: primitiveTokens.color.border,
    textPrimary: primitiveTokens.color.navy900,
    textSecondary: primitiveTokens.color.navy700,
    textSuccess: primitiveTokens.color.green500,
    textDanger: primitiveTokens.color.red500,
    tabBg: primitiveTokens.color.sky100,
    tabActiveBg: primitiveTokens.color.sky400,
    tabActiveText: primitiveTokens.color.white,
    buttonPrimaryBg: primitiveTokens.color.green500,
    buttonDangerBg: primitiveTokens.color.red300,
    buttonNeutralBg: primitiveTokens.color.sky200,
    buttonText: primitiveTokens.color.navy900,
    headerBg: primitiveTokens.color.blue950,
    headerText: primitiveTokens.color.white,
    headerSubText: primitiveTokens.color.sky100,
  },
  space: {
    xs: primitiveTokens.space[8],
    sm: primitiveTokens.space[12],
    md: primitiveTokens.space[16],
    lg: primitiveTokens.space[20],
    xl: primitiveTokens.space[24],
    xxl: primitiveTokens.space[32],
    pageTop: primitiveTokens.space[40],
    pageBottom: primitiveTokens.space[64],
    pagePadding: primitiveTokens.space[32],
    sectionGap: primitiveTokens.space[24],
    panelPadding: primitiveTokens.space[24],
    cardPadding: primitiveTokens.space[24],
    buttonPaddingX: primitiveTokens.space[20],
    buttonPaddingY: primitiveTokens.space[12],
  },
  radius: {
    panel: primitiveTokens.radius.xl,
    card: primitiveTokens.radius.lg,
    button: primitiveTokens.radius.pill,
    pill: primitiveTokens.radius.pill,
    round: primitiveTokens.radius.round,
  },
  font: {
    family: "'Pretendard', 'Apple SD Gothic Neo', 'Noto Sans KR', 'Segoe UI', sans-serif",
    headingLg: primitiveTokens.fontSize[32],
    headingMd: primitiveTokens.fontSize[24],
    bodyMd: primitiveTokens.fontSize[16],
    labelMd: primitiveTokens.fontSize[14],
    scoreXl: primitiveTokens.fontSize[56],
    weightMedium: primitiveTokens.fontWeight.medium,
    weightSemibold: primitiveTokens.fontWeight.semibold,
    weightBold: primitiveTokens.fontWeight.bold,
    lineHeightTight: primitiveTokens.lineHeight.tight,
    lineHeightNormal: primitiveTokens.lineHeight.normal,
  },
  shadow: {
    card: primitiveTokens.shadow.card,
    modal: primitiveTokens.shadow.modal,
  },
  size: {
    pageWidth: primitiveTokens.size.pageWidth,
    buttonHeight: primitiveTokens.size.buttonHeight,
    headerHeight: primitiveTokens.size.headerHeight,
    boardMaxWidth: primitiveTokens.size.boardMaxWidth,
  },
  motion: {
    fast: primitiveTokens.motion.fast,
    normal: primitiveTokens.motion.normal,
  },
});
