/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteRouteImport } from './routes/users/route'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as SigninRouteRouteImport } from './routes/signin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersMyRouteRouteImport } from './routes/users/my/route'
import { Route as UsersUserIdRouteRouteImport } from './routes/users/$userId/route'

const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRouteRoute = SigninRouteRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRouteRoute,
} as any)
const UsersMyRouteRoute = UsersMyRouteRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => UsersRouteRoute,
} as any)
const UsersUserIdRouteRoute = UsersUserIdRouteRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRouteRoute
  '/signup': typeof SignupRouteRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/users/$userId': typeof UsersUserIdRouteRoute
  '/users/my': typeof UsersMyRouteRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRouteRoute
  '/signup': typeof SignupRouteRoute
  '/users/$userId': typeof UsersUserIdRouteRoute
  '/users/my': typeof UsersMyRouteRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/signin': typeof SigninRouteRoute
  '/signup': typeof SignupRouteRoute
  '/users': typeof UsersRouteRouteWithChildren
  '/users/$userId': typeof UsersUserIdRouteRoute
  '/users/my': typeof UsersMyRouteRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/users'
    | '/users/$userId'
    | '/users/my'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup' | '/users/$userId' | '/users/my' | '/users'
  id:
    | '__root__'
    | '/'
    | '/signin'
    | '/signup'
    | '/users'
    | '/users/$userId'
    | '/users/my'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SigninRouteRoute: typeof SigninRouteRoute
  SignupRouteRoute: typeof SignupRouteRoute
  UsersRouteRoute: typeof UsersRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/users/my': {
      id: '/users/my'
      path: '/my'
      fullPath: '/users/my'
      preLoaderRoute: typeof UsersMyRouteRouteImport
      parentRoute: typeof UsersRouteRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteRouteImport
      parentRoute: typeof UsersRouteRoute
    }
  }
}

interface UsersRouteRouteChildren {
  UsersUserIdRouteRoute: typeof UsersUserIdRouteRoute
  UsersMyRouteRoute: typeof UsersMyRouteRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteRouteChildren: UsersRouteRouteChildren = {
  UsersUserIdRouteRoute: UsersUserIdRouteRoute,
  UsersMyRouteRoute: UsersMyRouteRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteRouteWithChildren = UsersRouteRoute._addFileChildren(
  UsersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SigninRouteRoute: SigninRouteRoute,
  SignupRouteRoute: SignupRouteRoute,
  UsersRouteRoute: UsersRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
